# Generated by Django 6.0.3 on 2026-03-21 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_payment"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
        migrations.DeleteModel(
            name="Payment",
        ),
    ]
