# Generated by Django 6.0.3 on 2026-04-03 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0002_course_owner_lesson_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="last_notification_sent",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
